server:
  port: 8080
  mode: dev
  driverName: mysql
logger:
  logLevel: debug
  fileName: "./storage/logs/server.log"
  maxSize: 500 # megabytes
  maxBackups: 3
  maxAge: 28 #days
  compress: true # disabled by default
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  databaseName: ecommerce_go
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
redis:
  host: localhost
  port: 6379
  password: 
  database: 0
  poolSize: 10
kafka:
  host: localhost
  port: 9094
email:
  host: "smtp.gmail.com"
  port: 587
  user: "tuan.thanhoanganh@gmail.com"
  password: "ytfs mrsc ybci snhb"
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "API_SECRET"